Numpy is python library. It is used to perform numerical operations. Arithematic operations, logical operations. we can also create array with the use of numpy array and some other opertaions will be performed.
    

In [ ]:
import numpy as np
## importing numpy library


create array

In [1]:
import numpy as np

Arr = np.array([13,4,7,4,67,3,8])

print("Array is:", Arr)

Array is: [13  4  7  4 67  3  8]


Operations on array


In [2]:
sum = Arr + Arr
sum

array([ 26,   8,  14,   8, 134,   6,  16])

In [4]:
Mul = Arr * Arr
Mul

array([ 169,   16,   49,   16, 4489,    9,   64])

In [5]:
Sub = Arr - Arr
Sub

array([0, 0, 0, 0, 0, 0, 0])

In [6]:
Divide = Arr / Arr
Divide

array([1., 1., 1., 1., 1., 1., 1.])